version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgresdb
    volumes:
      - postgres-data:/var/lib/postgresql

  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://root:rootpassword@mongodb:27017/
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=postgresdb
    depends_on:
      - mongodb
      - postgres
    volumes:
      - ./BACKEND:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongo-data:
  postgres-data:
